# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d9d283ad52b6c6617eda8fa3b25834c3f11756afea8c9033e9c96d4e70fc55d0bfd4265d8dc0cf72b84751e4d99a7f8aec78cee484bc46587511164896543f68

test:
  secret_key_base: e655b7a825101a4dc9b9f3c578cc1ba216f6f6b6da52dc7e415555c60a9f83068c0e7a5087784fd4a9cf57f3094bd92a4ccae5999841784c2f546ebb9bc9d2bc

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
